### PR TITLE
BREAKING CHANGE: Remove distribution of fonts

### PR DESCRIPTION
**Pull request by grandorf**
This one has high priority because we are distributing our fonts which we are not allowed to.

### CODE REVIEW

**Review by razvandk — APPROVED** [review]
Looks good, but where are we going to get our fonts from?

**Comment by havgry** [comment]
@razvandk //s.c.dk/fonts/*, I guess. I see that the font-face rules are still pointing to that. I think this is just a reaction to outright distributing it in DNA.

**Review by havgry — APPROVED** [review]
Looks okay for now. I understand if you want this merged quickly. I would like this to be followed up by something in the documentation... Anything... That outlines the changes from version 2 to 3.

**Comment by grandorf** [comment]
> @razvandk //s.c.dk/fonts/*, I guess. I see that the font-face rules are still pointing to that. I think this is just a reaction to outright distributing it in DNA.

Exactly. The DNA components are using CDN. We just added the fonts as an extra feature.

**Comment by grandorf** [comment]
> Looks okay for now. I understand if you want this merged quickly. I would like this to be followed up by something in the documentation... Anything... That outlines the changes from version 2 to 3.

I will make sure to highlight this change in GitHub and in our changelog https://dna.yousee.dk/docs/changelog.

**Pull request merged**
