### PR TITLE
Fix discrepancies in list components in Fractal

### PR DESCRIPTION
**Pull request by havgry**
As we're not using `list-style` at all it makes sense to explicitly set it to `none` to avoid conflicts as it's pretty common to have general list styles as part of one's base styles (see conflict with Fractal styles). Furthermore, it's already set for the list mixin, so this is just an extension of that decision.

This fixes https://jira.tdc.dk/browse/YDS-608, although I'm not sure if there are other aspects of the list that needs to be looked into like `line-height` which seems slightly off.

### CODE REVIEW

**Comment by havgry** [comment]
Apparently, I have the memory of a brick. I totally forgot about the existence of https://github.com/youseedk/dna/pull/162

I've updated this PR to also include a couple of fixes for the list components:

- Remove Fractal bottom margin to list items
- Prevent general Fractal font-size from cascading into DNA components (the lists were 20px instead of 16px). This could have affected other components as well.
- Fix unordered list marker indentation

This basically means the old PR can be closed without merging.

**Comment by grandorf** [comment]
I think your changes conflicted a little bit with some of my fractal theming I just did. Can you sort it out?

**Comment by grandorf** [comment]
Looks like this is the conflict. I changed the fontsize from 20px to 18px (or 1.125rem).
image

**Comment by havgry** [comment]
Fixed :)

**Pull request merged**
